# Sample config for Prometheus.

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'external'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['prometheus.aidevops.dev:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  #- "rules.yml"
  - "alert_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['prometheus.aidevops.dev:9090', 'prometheus.aidevops.dev:9100']

  - job_name: 'python_app'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['prometheus.aidevops.dev:8000']

  - job_name: 'master'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['master101.aidevops.dev:9100', 'master102.aidevops.dev:9100', 'master103.aidevops.dev:9100']
