global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files: <1>
 - rules.yml
alerting: <2>
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:9093
scrape_configs: <3>
 - job_name: prometheus
   static_configs:
    - targets:
       - localhost:9090
 - job_name: node
   static_configs:
    - targets:
       - localhost:9100
