global:
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  evaluation_interval: 15s
  external_labels:
    monitor: external
runtime:
  gogc: 75

# Alerting manager  
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    http_headers: null
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - 4225a859241c.mylabserver.com:9093
rule_files:
- /etc/prometheus/alert_rules.yml

# Prometheus monitoring
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 5s
  scrape_timeout: 5s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  basic_auth:
    username: prometheus
    password: bWFuLXNpbmgtbGVlQE1hY01pbmkK
  tls_config:
    cert_file: /etc/prometheus/fullchain.pem
    key_file: /etc/prometheus/privkey.pem
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  http_headers: null
  metric_relabel_configs:
  - separator: ;
    regex: container_label_.*
    replacement: $1
    action: labeldrop
  static_configs:
  - targets:
    - 4225a859241c.mylabserver.com:9090

# Pushgateway monitoring    
- job_name: pushgateway
  honor_labels: true
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  http_headers: null
  static_configs:
  - targets:
    - 4225a859241c.mylabserver.com:9091

# MySQL monitoring    
- job_name: mysql
  honor_labels: true
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  http_headers: null
  static_configs:
  - targets:
    - 4225a859241c.mylabserver.com:9104
    - 4225a859242c.mylabserver.com:9104
    - 4225a859243c.mylabserver.com:9104
    - 4225a859244c.mylabserver.com:9104

# Nginx backend montoring    
- job_name: nginx_exporter
  honor_labels: true
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  http_headers: null
  static_configs:
  - targets:
    - 4225a859241c.mylabserver.com:9113
    - 4225a859242c.mylabserver.com:9113
    - 4225a859243c.mylabserver.com:9113
    - 4225a859244c.mylabserver.com:9113

# ElasticSearch Nodes monitoring    
- job_name: elk
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 5s
  scrape_timeout: 5s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  http_headers: null
  static_configs:
  - targets:
    - 4225a859241c.mylabserver.com:9100
    - 4225a859242c.mylabserver.com:9100
    - 4225a859243c.mylabserver.com:9100
    - 4225a859244c.mylabserver.com:9100

# Blackbox ICMP monitorng
- job_name: blackbox_icmp
  honor_timestamps: true
  track_timestamps_staleness: false
  params:
    module:
    - icmp
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /probe
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  http_headers: null
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: 4225a859241c.mylabserver.com:9115
    action: replace
  static_configs:
  - targets:
    - 4225a859241c.mylabserver.com
    - 4225a859242c.mylabserver.com
    - 4225a859243c.mylabserver.com
    - 4225a859244c.mylabserver.com

# Blackbox SSH monitoring    
- job_name: blackbox_ssh
  honor_timestamps: true
  track_timestamps_staleness: false
  params:
    module:
    - ssh_banner
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /probe
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  http_headers: null
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: 4225a859241c.mylabserver.com:9115
    action: replace
  static_configs:
  - targets:
    - 4225a859241c.mylabserver.com:22
    - 4225a859242c.mylabserver.com:22
    - 4225a859243c.mylabserver.com:22
    - 4225a859244c.mylabserver.com:22

# Blackbox TCP monitoring    
- job_name: blackbox_tcp
  honor_timestamps: true
  track_timestamps_staleness: false
  params:
    module:
    - tcp_connect
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /probe
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  http_headers: null
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: 4225a859241c.mylabserver.com:9115
    action: replace
  static_configs:
  - targets:
    - 4225a859241c.mylabserver.com:3306
    - 4225a859242c.mylabserver.com:3306
    - 4225a859243c.mylabserver.com:3306
    - 4225a859244c.mylabserver.com:3306

# Blackbox HTTPs monitoring    
- job_name: blackbox_https
  honor_timestamps: true
  track_timestamps_staleness: false
  params:
    module:
    - https_2xx
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /probe
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  http_headers: null
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: 4225a859241c.mylabserver.com:9115
    action: replace
  static_configs:
  - targets:
    - oreilly.com
    - prometheus.io
    - cia.gov

# Blackbox DNS monitoring    
- job_name: blackbox_dns
  honor_timestamps: true
  track_timestamps_staleness: false
  params:
    module:
    - dns_tcp
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /probe
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  http_headers: null
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: 4225a859241c.mylabserver.com:9115
    action: replace
  static_configs:
  - targets:
    - 1.0.0.1
    - 1.1.1.1
    - 8.8.4.4
    - 8.8.8.8
